name: Testing GSheets to Website

on: workflow_dispatch

env:
  SHEET_ID: '1fvz34wY6phWDJsuIneqvOoZRPfo6CfJyPg1BYgHt59k'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v3

#       - name: Run a one-line script
#         run: echo Starting testing GSheets to Website
        
        - id: googlesheet_actions
          uses: rjoydip/googlesheet-actions@0.1.1
          with:
            sheet-id: ${{ env.SHEET_ID }}
            
        - id: echo
          uses: actions/github-script@v2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                console.log(${{steps.googlesheet_actions.outputs.result}})
                
        - name: test
          run: |
            cat $HOME/data.json
            
#       - name: Pull GSheet data
#         id: 'sheet_to_csv'
#         uses: dolthub/gsheets-to-csv@v0.1
#         with:
#           creds: ${{ secrets.GSHEET_CREDENTIALS }}
#           sheets: |
#             [
#               { "id": "${{ env.id }}", "range": "${{ env.range }}", "title": "${{ env.name }}" },
#               { "id": "${{ env.id }}" }
#             ]
            
#       - name: Print CSV
#         id: "print_csv"
#         env:
#           FILES: ${{ steps.sheet_to_csv.outputs.results }}
#         run: |
#           file_list=($FILES)
#           for file in "${file_list[@]}"; do
#               echo "$(wc -l $file)"
#           done
